# Generated by Django 3.1.2 on 2020-10-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherRating', '0003_auto_20201009_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherrating',
            name='photo_path',
            field=models.FilePathField(path='/mnt/d/python/django/baumandays/static/src/pic/teacher_pic', verbose_name='photo path'),
        ),
    ]
