# Generated by Django 3.1.2 on 2020-10-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherRating', '0004_auto_20201009_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherrating',
            name='discipline_photo_path',
            field=models.FilePathField(default='/mnt/d/python/django/baumandays/static/src/pic/discipline_pic', path='/mnt/d/python/django/baumandays/static/src/pic/discipline_pic', verbose_name='discipline photo path'),
        ),
    ]
