# Generated by Django 3.1.2 on 2020-10-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherRating', '0005_teacherrating_discipline_photo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherrating',
            name='photo_path',
            field=models.FilePathField(path='src/pic/teacher_pic', verbose_name='photo path'),
        ),
    ]
