# Generated by Django 3.1.2 on 2020-10-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherRating', '0006_auto_20201015_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherrating',
            name='photo_path',
            field=models.FilePathField(path='/mnt/d/python/django/baumandays/static/src/pic/teacher_pic', verbose_name='photo path'),
        ),
    ]
