# Generated by Django 3.1.2 on 2020-11-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherRating', '0008_auto_20201127_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherrating',
            name='discipline_photo_path',
            field=models.ImageField(blank=True, max_length=256, upload_to='discipline_photo/', verbose_name='discipline photo'),
        ),
        migrations.AlterField(
            model_name='teacherrating',
            name='photo_path',
            field=models.ImageField(blank=True, max_length=256, upload_to='teacher_photo/', verbose_name='teacher photo'),
        ),
    ]
