# Generated by Django 3.1.2 on 2020-11-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherRating', '0009_auto_20201128_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherrating',
            name='discipline_photo_path',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacherrating',
            name='photo_path',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
